

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const CREATE_CHARACTER = 'CREATE_CHARACTER';
export const LOGOUT_CHARACTER = 'LOGOUT_CHARACTER';
export const GET_CHARACTER = 'GET_CHARACTER';
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const START_LOADING_RANKING = 'START_LOADING_RANKING';
export const END_LOADING_RANKING = 'END_LOADING_RANKING';
export const GET_RANKING_CHARACTER = 'GET_RANKING_CHARACTER';
export const GET_RANKING = 'GET_RANKING';
