export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const CREATE_CHARACTER = 'CREATE_CHARACTER';
export const LOGOUT_CHARACTER = 'LOGOUT_CHARACTER';
export const GET_CHARACTER = 'GET_CHARACTER';
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';

export const START_LOADING_CHARACTER = 'START_LOADING_CHARACTER';
export const END_LOADING_CHARACTER = 'END_LOADING_CHARACTER';

export const START_LOADING_RANKING = 'START_LOADING_RANKING';
export const END_LOADING_RANKING = 'END_LOADING_RANKING';
export const GET_RANKING_CHARACTER = 'GET_RANKING_CHARACTER';
export const GET_RANKING = 'GET_RANKING';

export const START_LOADING_ARENA = 'START_LOADING_ARENA';
export const END_LOADING_ARENA = 'END_LOADING_ARENA';
export const GET_ARENA = 'GET_ARENA';
export const REPLACE_MONSTER = 'REPLACE_MONSTER';
export const ADD_MONSTER = 'ADD_MONSTER';
export const REMOVE_MONSTER = 'REMOVE_MONSTER';
export const START_LOADING_MONSTER = 'START_LOADING_MONSTER';
export const END_LOADING_MONSTER = 'END_LOADING_MONSTER';
export const SET_FIGHT_LOG = 'SET_FIGHT_LOG';
